name: Build

on:
  workflow_dispatch:
jobs:  
  build:
    name: 'build-test on Haiku'
    runs-on: 'ubuntu-latest'
    container: 'docker.io/hectorm/qemu-haiku:latest'
    steps:
    - name: 'Wait until the VM is ready'
      run: 'container-init & timeout 600 vmshell exit 0'
    - name: 'Install packages'
      run: 'vmshell pkgman install -y make makefile_engine'
    - name: 'Reboot'
      run: 'sv force-restart qemu ||:; timeout 600 vmshell exit 0'
    - name: 'Checkout project'
      uses: actions/checkout@v3
    - name: 'Copy project to VM'
      run: 'vmshell mkdir ./src/; tar -cf - ./ | vmshell tar -xf - -C ./src/'
    - name: 'Build project'
      run: 'vmshell make -C ./src/'
