name: Build

on:
  workflow_dispatch:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:  
  build:
    name: 'build on Haiku'
    runs-on: 'ubuntu-latest'
    container: 'docker.io/hectorm/qemu-haiku:latest'
    steps:
    - name: 'Wait until the VM is ready'
      run: 'container-init & timeout 600 vmshell exit 0'
    - name: 'Setup tmate session'
      uses: 'mxschmitt/action-tmate@v3'
      with:
        limit-access-to-actor: true
        sudo: false
